version: '3.1'
services:
  mongo1:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    restart: always
    container_name: mongo1
  mongo2:
    image: mongo:4.0-xenial
    ports:
      - 27018:27017
    restart: always
    container_name: mongo2
  mongo3:
    image: mongo:4.0-xenial
    ports:
      - 27019:27017
    restart: always
    container_name: mongo3
