# Force dep to download subpackage with no Go code and only C files.
# This is because of issue https://github.com/golang/dep/issues/1306
required = [
  "github.com/ethereum/go-ethereum/crypto/secp256k1",
  #"github.com/karalabe/hid/libusb"
]

[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  version = "1.8.11"

[[constraint]]
  name = "github.com/go-stack/stack"
  version = "1.7.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/btcsuite/btcd"
