version: "3"
services:
  {node_name}:
    image: kardiachain/go-kardia
    logging:
      options:
        max-size: "300m"
    container_name: "{node_name}"
    ports:
      - 8545:8545
      - 3000:3000
      - 3000:3000/udp
      - 5555:5555
    volumes:
      - /tmp/kardiachain/{node_name}/data/db:/root/.kardia/{node_name}
    command: [
      "--dev",
      "--mainChainValIndexes",
      "4,5,6",
      "--dualChainValIndexes",
      "7,8,9",
      "--trondual",
      "--dualchain",
      "--addr",
      ":3000",
      "--name",
      "{node_name}",
      "--rpc",
      "--clearDataDir",
      "--publishedEndpoint",
      "tcp://dual-tron:5554",
      "--subscribedEndpoint",
      "tcp://0.0.0.0:5555",
      "--peer",
      "{peer}"
    ]
  dual-tron:
    image: kardiachain/dual-tron
    logging:
      options:
        max-size: "300m"
    container_name: "dual-tron"
    ports:
      - 18191:18191
      - 50051:50051
      - 5554:5554
    volumes:
      - /tmp/kardiachain/dual-tron/resources/fullnode.conf:/app/target/resources/fullnode.conf
      - /tmp/kardiachain/dual-tron/output-directory:/app/output-directory
      - /tmp/kardiachain/dual-tron/logs:/app/logs
    environment:
        SUB_ADDRESS: tcp://0.0.0.0:5554
        PUB_ADDRESS: tcp://{node_name}:5555
    command: [
      "-c",
      "/app/target/resources/fullnode.conf",
    ]
