version: "3"
services:
  {node_name}:
    image: kardiachain/go-kardia
    logging:
      options:
        max-size: "300m"
    container_name: "{node_name}"
    ports:
      - 8545:8545
      - 3000:3000
      - 3000:3000/udp
      - 5555:5555
    volumes:
      - /tmp/kardiachain/{node_name}/data/db:/root/.kardia/{node_name}
    command: [
      "--dev",
      "--mainChainValIndexes",
      "4,5,6",
      "--dualChainValIndexes",
      "4,5,6",
      "--neodual",
      "--dualchain",
      "--addr",
      ":3000",
      "--name",
      "{node_name}",
      "--rpc",
      "--clearDataDir",
      "--publishedEndpoint",
      "tcp://neo_api_server:5554",
      "--subscribedEndpoint",
      "tcp://0.0.0.0:5555",
      "--peer",
      "{peer}"
    ]
  neo_api_server:
    image: kardiachain/neo-api-server-privnet
    logging:
      options:
        max-size: "300m"
    container_name: "neo_api_server"
    ports:
      - 5000:5000
      - 5554:5554
      - 8080:8080
    volumes:
      - ${PWD}/neo/privnet.json:/neo_api_server/src/data/protocol.privnet.docker.json
      - /tmp/kardiachain/{node_name}/Chains:/root/.neopython/Chains
    command: [
      "--published-endpoint",
      "tcp://{node_name}:5555"
    ]
